USE friend_db;

INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Blake',5,1,1,1,0,1,1,'https://www.petfinder.com/wp-content/uploads/2012/11/140272627-grooming-needs-senior-cat-632x475.jpg');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Bobbi',6,0,1,1,0,1,1,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAt9AxA9KNgK7Nhud4DLB1AUlteD_9vLsmFFNYj0B5RJPFOhB0A');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Max',5,1,1,0,0,1,1,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7FGyz0FrIGvx1QZ13DZ3MQoR4GBlrHWGh-cjsxjYTtFM6puDd');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Sylvester',6,1,0,1,0,1,1,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSFtIodZqaIFJ7HdqXRtTGeSv2mXGPceva2ojqV2pY3KUR5mSELgQ');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Bo',6,1,1,1,0,0,1,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcNnJvStl00Dt0RHnND60ygewz42NZIAh6Kw07bm6u4kIDZ9BX');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Tamme',5,1,0,1,0,1,1,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRYXNLuN8M8-f0TZUM9DIiMD3bNN6B8hyvlyttFrUdN423bn7ZD');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Tabby',7,1,0,1,0,1,0,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR9Fq73QS1XN04eTGug8bPOLzSskxysMj5qWQ9GMMo3mUxgQLBz');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Chittu',7,1,1,1,0,1,0,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTH1vhFCZx9q6PNKrOKRMrbXfZAalbTka4pOFnZznwkm2EygQR0');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Mani',5,1,1,1,0,1,0,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS8qkelB28RstsNxLi7gbrwCLsBVmobPjb5IrwKJSuqSnGX4IzX');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Alley',5,1,1,1,0,1,1,'https://www.petfinder.com/wp-content/uploads/2012/11/140272627-grooming-needs-senior-cat-632x475.jpg');
INSERT INTO friend (username ,	age ,	likestuna ,	likeschicken ,	likessalmon ,	likespurina ,	likesfancyfeast ,likesbeyond,	picture) VALUES ('Millie',6,1,1,1,0,0,1,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTZmNMvGoUC5ypAeel-sYr4poKXmO16ykCIgkjI1rkeUaEMLpDF5Q');
